# Demo1,understand basic python
print('Hello World!')
print('What is your name?')
myName=input()
print('It is good to meet you,'+myName)
print('The length of your name is:')
print(len(myName))
print('What is your age?')
age=input()
print('you will be '+ str(int(age)+1) +' in a year')
